Websitebansach/Controllers/QuanLiSanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Websitebansach.Models;
using PagedList;
using PagedList.Mvc;
using System.IO;
using System.Web.UI.WebControls;

namespace Websitebansach.Controllers
{
	public class QuanLiSanPhamController : Controller
	{
		// GET: QuanLiSanPham
		QuanLyBanSachEntities db = new QuanLyBanSachEntities();
		public ActionResult Index(int? page)
		{

			int pageNumber = (page ?? 1);
			int pageSize = 10;
			return View(db.Saches.ToList().OrderBy(n => n.MaSach).ToPagedList(pageNumber, pageSize));
		}
		//thêm mới
		[HttpGet]
		public ActionResult ThemMoi()
		{
			//Đưa dữ liệu vào
			ViewBag.MaChude = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "MaChuDe", "TenChuDe");
			ViewBag.MaNXB = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB");
			return View();
		}
		[HttpPost]
		[ValidateInput(false)]
		public ActionResult ThemMoi(Sach sach, HttpPostedFileBase fileUpload)
		{

			//Đưa dữ liệu vào
			ViewBag.MaChude = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "MaChuDe", "TenChuDe");
			ViewBag.MaNXB = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB");

			//thêm dữ liệu vào
			if (ModelState.IsValid)
			{
				//Lưu tên của file
				var fileName = Path.GetFileName(fileUpload.FileName);
				//Lưu đường dẫn của file
				var path = Path.Combine(Server.MapPath("~/HinhAnh"), fileName);
				if (System.IO.File.Exists(path))
				{
					ViewBag.ThongBao = "Hình ảnh đã tồn tại";
				}
				else
				{
					fileUpload.SaveAs(path);
				}
				sach.AnhBia = fileUpload.FileName;
				db.Saches.Add(sach);
				db.SaveChanges();
			}

			return View();
		}

		//chỉnh sửa
		[HttpGet]
		public ActionResult ChinhSua(int MaSach)
		{
			Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == MaSach);
			if (sach == null)
			{
				Response.StatusCode = 404;
				return null;
			}
			//Đưa dữ liệu vào
			ViewBag.MaChude = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "MaChuDe", "TenChuDe");
			ViewBag.MaNXB = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB");
			return View(sach);
		}
		[HttpPost]
		[ValidateInput(false)]
		public ActionResult ChinhSua(Sach sach, FormCollection f)
		{
			//thêm vào cở sở dữ liệu


			if (ModelState.IsValid)
			{
				//Thực hiện cập nhật model
				db.Entry(sach).State = System.Data.Entity.EntityState.Modified;
				db.SaveChanges();
			}
			//Đưa dữ liệu vào
			ViewBag.MaChude = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "MaChuDe", "TenChuDe");
			ViewBag.MaNXB = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB");

			return RedirectToAction("Index");
		}
		public ActionResult HienThi(int MaSach)
		{
			Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == MaSach);
			if (sach == null)
			{
				Response.StatusCode = 404;
				return null;
			}

			return View(sach);
		}
		//xóa sản phẩm 
		[HttpGet]
		public ActionResult Xoa(int MaSach)
		{
			Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == MaSach);
			if (sach == null)
			{
				Response.StatusCode = 404;
				return null;
			}

			return View(sach);
		}
		[HttpPost, ActionName("Xoa")]
		public ActionResult XacNhanXoa(int MaSach)
		{
			Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == MaSach);
			if (sach == null)
			{
				Response.StatusCode = 404;
				return null;
			}
			db.Saches.Remove(sach);
			db.SaveChanges();
			return RedirectToAction("Index");
		}
	}

}

Websitebansach/Views/QuanLiSanPham/ChinhSua.cshtml
@model Websitebansach.Models.Sach

@{
    ViewBag.Title = "ChinhSua";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>Chỉnh sửa</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Sach</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.MaSach, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <span>@Model.MaSach</span>
            @Html.Hidden("MaSach", Model.MaSach)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TenSach, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenSach, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenSach, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GiaBan, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GiaBan, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GiaBan, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.AnhBia, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="fileUpload" />
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NgayCapNhat, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NgayCapNhat, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NgayCapNhat, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SoLuongTon, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SoLuongTon, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SoLuongTon, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MaNXB, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("MaNXB")

        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MaChuDe, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("MaChuDe")

        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Moi, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Moi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Moi, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.MoTa, new { @class = "form-control", @rows = "5", @style = "resize: none;" })
            @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group" style="margin-top: 20px;">
        <div class="col-md-offset-2 col-md-10" style="margin-left: 16.6667%; width: 83.3333%;">
            <input type="submit" value="Lưu" class="btn" style="
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            font-size: 16px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        " onmouseover="this.style.backgroundColor='#0056b3';" onmouseout="this.style.backgroundColor='#007bff';" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Websitebansach/Views/QuanLiSanPham/HienThi.cshtml
@model Websitebansach.Models.Sach

@{
    ViewBag.Title = "HienThi";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>HienThi</h2>

<div>
    <h4>Sach</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaSach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaSach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenSach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaBan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaBan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnhBia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnhBia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayCapNhat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayCapNhat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuongTon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuongTon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhaXuatBan.TenNXB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhaXuatBan.TenNXB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChuDe.TenChuDe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChuDe.TenChuDe)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Moi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Moi)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Chỉnh sửa", "ChinhSua", new {MaSach=Model.MaSach }) |
    @Html.ActionLink("Quay về", "Index")
</p>

Websitebansach/Views/QuanLiSanPham/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model PagedList.PagedList<Websitebansach.Models.Sach>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>Danh sách tất cả các sách</h2>

<p>
    @Html.ActionLink("Thêm mới sách", "ThemMoi")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().MaSach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().TenSach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().GiaBan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().MoTa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().AnhBia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().NgayCapNhat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().SoLuongTon)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().MaNXB)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().MaChuDe)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Moi)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MaSach)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TenSach)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GiaBan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MoTa)
            </td>
            <td>
                <div id="AnhBia"><img src="@Url.Content("~/HinhAnh/"+item.AnhBia)" width="150" height="150"/> </div>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayCapNhat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoLuongTon)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NhaXuatBan.TenNXB)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaChuDe)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Moi)
            </td>
            <td>
                @Html.ActionLink("Chỉnh sửa", "ChinhSua", new { @MaSach=item.MaSach  }) |
                @Html.ActionLink("Xem chi tiết ", "HienThi", new { @MaSach = item.MaSach }) |
                @Html.ActionLink("Xóa", "Xoa", new { @MaSach = item.MaSach })
            </td>
        </tr>
    }

</table>
Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/ @Model.PageCount;
<div class="MenuTrang">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
</div>
<style>
    .MenuTrang li {
        display: inline;
    }
</style>

Websitebansach/Views/QuanLiSanPham/ThemMoi.cshtml
@model Websitebansach.Models.Sach

@{
    ViewBag.Title = "ThemMoi";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>Thêm sách mới</h2>
@*Thêm thuộc tính cho forrm*@
@using (Html.BeginForm("ThemMoi","QuanLiSanPham",FormMethod.Post, new {@enctype ="multipart/form-data"})) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Sách</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.MaSach, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MaSach, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MaSach, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TenSach, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenSach, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenSach, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GiaBan, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GiaBan, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GiaBan, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.AnhBia, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
           <input type="file" name="fileUpload" />
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NgayCapNhat, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NgayCapNhat, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NgayCapNhat, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SoLuongTon, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SoLuongTon, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SoLuongTon, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MaNXB, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("MaNXB")
           
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MaChuDe, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("MaChuDe")
       
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Moi, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Moi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Moi, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" style="margin-top: 20px;">
        <div class="col-md-offset-2 col-md-10" style="margin-left: 16.6667%; width: 83.3333%;">
            <input type="submit" value="Thêm mới" class="btn" style="
                padding: 10px 20px;
                background-color: #007bff;
                color: #fff;
                border: none;
                border-radius: 5px;
                font-size: 16px;
                cursor: pointer;
                transition: background-color 0.3s ease;
            " onmouseover="this.style.backgroundColor='#0056b3';" onmouseout="this.style.backgroundColor='#007bff';" />
        </div>
    </div>
</div>    
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Websitebansach/Views/QuanLiSanPham/Xoa.cshtml
@model Websitebansach.Models.Sach

@{
    ViewBag.Title = "Xoa";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>Xoa</h2>

<h3>Bạn có thực sự muốn xóa sách này ?</h3>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaSach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaSach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenSach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaBan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaBan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnhBia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnhBia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayCapNhat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayCapNhat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuongTon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuongTon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhaXuatBan.TenNXB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhaXuatBan.TenNXB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChuDe.TenChuDe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChuDe.TenChuDe)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Moi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Moi)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <div class="col-md-offset-2 col-md-10" style="margin-left: 16.6667%; width: 83.3333%;">
                <input type="submit" value="Xóa" class="btn" style="
                padding: 10px 20px;
                background-color: #007bff;
                color: #fff;
                 border: none;
                border-radius: 5px;
                font-size: 16px;
                cursor: pointer;
                transition: background-color 0.3s ease;
                " onmouseover="this.style.backgroundColor='#0056b3';" onmouseout="this.style.backgroundColor='#007bff';" />
            </div>
            @Html.ActionLink("Quay về", "Index")
        </div>
    }
</div>