Websitebansach/Websitebansach/Websitebansach/Controllers/ChudeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Websitebansach.Models;

namespace Websitebansach.Controllers
{
    public class ChudeController : Controller
    {
        QuanLyBanSachEntities db = new QuanLyBanSachEntities();
        // GET: Chude
        public PartialViewResult ChudePartial()
        {
            return PartialView(db.ChuDes.Take(9).ToList());
        }
        public ViewResult SachTheoChuDe(int MaChuDe = 0)
        {
            ChuDe cd = db.ChuDes.SingleOrDefault(n => n.MaChuDe == MaChuDe);
            if (cd == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            List<Sach> lsach = db.Saches.Where(n => n.MaChuDe == MaChuDe).OrderBy(n => n.GiaBan).ToList();
            if (lsach.Count == 0)
            {
                ViewBag.Sach = "Không có sách cho chủ đề này";
            }
            return View(lsach);
        }
    }
}

Websitebansach/Websitebansach/Websitebansach/Controllers/NhaXuatBanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Websitebansach.Models;
namespace Websitebansach.Controllers
{
    public class NhaXuatBanController : Controller
    {
        QuanLyBanSachEntities db = new QuanLyBanSachEntities();
        // GET: NhaXuatBan
        public PartialViewResult NhaXuatBanPartial()
        {
            return PartialView(db.NhaXuatBans.Take(10).OrderBy(n=>n.TenNXB).ToList());
        }
		public ViewResult SachTheoNXB(int MaNXB = 0)
		{
			//kiểm tra nhà xuất bản có tồn tại?
			NhaXuatBan nxb = db.NhaXuatBans.SingleOrDefault(n => n.MaNXB == MaNXB);
			if (nxb == null)
			{
				Response.StatusCode = 404;
				return null;
			}
			//truy xuất các quyển sách theo nhà xuất bản
			List<Sach> sach = db.Saches.Where(n => n.MaNXB == MaNXB).OrderBy(n => n.GiaBan).ToList();
			if (sach.Count == 0)
			{
				ViewBag.sach = "Không có sách gì trong chủ đề này";
			}
			return View(sach);
		}
	}
}

Websitebansach/Websitebansach/Websitebansach/Controllers/SachController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Websitebansach.Models;
namespace Websitebansach.Controllers
{
	
    public class SachController : Controller
    {
		QuanLyBanSachEntities db = new QuanLyBanSachEntities();
		// GET: Sach
		public PartialViewResult SachmenuPartial()
		{
			var listsach = db.Saches.Take(3).ToList();
			return PartialView(listsach);
		}
		public ViewResult XemChiTiet(int MaSach=0)
		{
			Sach sach = db.Saches.SingleOrDefault(n=>n.MaSach == MaSach);
			if (sach == null)
			{
				Response.StatusCode = 404;
				return null;
			}
			return View(sach);
		}
	}
}

Websitebansach/Websitebansach/Websitebansach/Views/Layout/NguoidungLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/NguoidungLayoutcss/fonts.css" rel="stylesheet" />
    <link href="~/Content/NguoidungLayoutcss/screen.css" rel="stylesheet" />
    <link href="~/Content/NguoidungLayoutcss/NguoidungLayoutcss.css" rel="stylesheet" />
    <link href="~/Content/Fontweasome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/NivoSilder/nivo-slider.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/NivoSilder/jquery.nivo.slider.js"></script>
    <script src="~/NivoSilder/jquery.nivo.slider.pack.js"></script>


</head>

<body>

    <div id="Toantrang">

        <section class="blank">
            <div class="flash">
                <div class="icDienThoai">
                    <i class=" fa fa-phone" aria-hidden="true"></i>
                    (08)123-345
                </div>

                <div class="DangkyDangnhap">
                    <i class="fa fa-sign-in" aria-hidden="true"></i>
                    @Html.ActionLink("Đăng Ký", "Dangky", null, htmlAttributes: new { @class = "Dangky" })
                    <i class="fa fa-unlock" aria-hidden="true"></i>
                    @Html.ActionLink("Đăng Nhập", "Dangnhap", null, htmlAttributes: new { @class = "Dangnhap" })
                </div>
            </div>


            <div class="flash success" id="divDanhMuc">
                <div id="txtTimKiem">
                    @using (Html.BeginForm())
                    {
                        @Html.TextBox("txtTimKiem", "", htmlAttributes: new { @class = "TextBoxTimKiem", @placeholder = "Nhập vào từ khóa cần tìm" })
                        <div id="divHinhAnhTimKiem">
                            <button type="submit"><img src="~/HinhAnh/freesearch.png" /> </button>
                        </div>

                    }
                </div>
                <ul class=" navMenu">
                    <li>
                        <a href="@Url.Action("Index","Home")">Trang Chủ</a>
                    </li>
                    <li>
                        <a href="#">Giới Thiệu</a>
                    </li>
                    <li>
                        <a href="#">Liên Hệ</a>
                    </li>
                    <li>
                        <a href="#">Hướng dẫn </a>
                    </li>
                    <li>
                        <a href="#">Sách</a>
                    </li>
                </ul>


            </div>
        </section>
        <section>
            <div>
                @Html.Action("ChudePartial", "Chude")
            </div>

            <hr>


            <hr>


        </section>
        <section>
            <div id="divMenuLeft">
                <div class="activity">
                    @Html.Action("SachmenuPartial", "Sach")

                </div>
            </div>
            <div id="slider" class="nivoslider">
                <img src="~/HinhAnh/banner2.jpg" />

            </div>
            <div style="clear:both"></div>
        </section>
        <div id="NoiDung">
            @RenderBody()
        </div>

        <div style="clear:both"></div>
        <section class="blank items">
            <div class="item">

                <div id="divLeft">
                    <div class="item-info">
                        @Html.Action("NhaXuatBanPartial", "NhaXuatBan")
                    </div>

                    
                </div>

                <div style="clear:both"></div>

            </div>

            <div id="divRight">
                @RenderSection("Noidungbenphai", false)
            </div>

            <div>
                <a href="#" class="button button-buy">Chào mừng các bạn  đến với website bán sách</a>
            </div>
        </section>

        <script type="text/javascript">
            $(window).load(function () {
                $('#slider').nivoSlider();
            });
        </script>
</body>
</div>
</html>